language: node_js
node_js:
  - "7"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod
  - make dist
  
deploy:
  provider: releases
  api_key: ${api-key}
  file: release.zip
  skip_cleanup: true
  on:
    tags: true
